//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokedex.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pokedex.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id,identifier,species_id,height,weight,base_experience,order,is_default
        ///1,bulbasaur,1,7,69,64,1,1
        ///2,ivysaur,2,10,130,142,2,1
        ///3,venusaur,3,20,1000,236,3,1
        ///4,charmander,4,6,85,62,5,1
        ///5,charmeleon,5,11,190,142,6,1
        ///6,charizard,6,17,905,240,7,1
        ///7,squirtle,7,5,90,63,10,1
        ///8,wartortle,8,10,225,142,11,1
        ///9,blastoise,9,16,855,239,12,1
        ///10,caterpie,10,3,29,39,14,1
        ///11,metapod,11,7,99,72,15,1
        ///12,butterfree,12,11,320,178,16,1
        ///13,weedle,13,3,32,39,17,1
        ///14,kakuna,14,6,100,72,18,1
        ///15,beedrill,15,10,295,178,19,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pokemon {
            get {
                return ResourceManager.GetString("Pokemon", resourceCulture);
            }
        }
    }
}
